import fs from "fs";
import axios from "axios";
import { getAccessToken } from "./tokenManager.js";
import dotenv from "dotenv";
dotenv.config();

const ORG_ID = process.env.ZOHO_ORG_ID || "688156835";
const DEPT_ID = process.env.ZOHO_DEPT_ID || "388402000000006907";
const DC = process.env.ZOHO_DC || "com";
const DESK_BASE = `https://desk.zoho.${DC}/api/v1`;

// --- Helper: Read stored tokens (for debugging only) ---
export function getTokens() {
  try {
    if (fs.existsSync("zoho_tokens.json")) {
      const data = fs.readFileSync("zoho_tokens.json", "utf-8");
      return JSON.parse(data);
    }
  } catch (err) {
    console.error("⚠️ Failed to read Zoho tokens:", err.message);
  }
  return null;
}

// --- Helper: find or create a contact in Zoho ---
async function findOrCreateContact(accessToken, { email, lastName = "User", firstName = "" }) {
  try {
    const q = encodeURIComponent(`email:${email}`);
    const resp = await axios.get(`${DESK_BASE}/contacts/search?searchStr=${q}`, {
      headers: { Authorization: `Zoho-oauthtoken ${accessToken}`, orgId: ORG_ID },
    });
    if (Array.isArray(resp.data?.data) && resp.data.data.length) {
      console.log("👤 Existing Zoho contact found:", email);
      return resp.data.data[0];
    }
  } catch (err) {
    console.warn("ℹ️ Contact not found, creating new one...");
  }

  const { data } = await axios.post(
    `${DESK_BASE}/contacts`,
    { email, lastName, firstName },
    {
      headers: {
        Authorization: `Zoho-oauthtoken ${accessToken}`,
        orgId: ORG_ID,
        "Content-Type": "application/json",
      },
    }
  );
  console.log("🆕 Created new Zoho contact:", email);
  return data;
}

// === Main Function ===
export async function createZohoTicket(userName, userEmail, message) {
  try {
    const accessToken = await getAccessToken();
    if (!accessToken) {
      console.log("⚠️ Zoho access token could not be retrieved");
      return "❌ Unable to create ticket — Zoho authentication failed.";
    }
    const contact = await findOrCreateContact(accessToken, {
      email: userEmail,
      lastName: userName,
    });

    // === Ticket payload ===
    const ticketData = {
      subject: `[QueryTel Sentinel] Security Alert - Action Required`,
      description: `
  <div style="font-family: Arial, sans-serif; color: #222;">
    <h2>🚨 <b>Security Alert Report</b></h2>
    <p><b>Generated by:</b> QueryTel Sentinel SOC</p>
    <p><b>Reported By:</b> ${userName || "Unknown User"} &lt;${userEmail || "N/A"}&gt;</p>
    <hr>
    <h3>⚠️ Alert Summary</h3>
    <p>${message || "No additional context provided."}</p>
    <hr>
    <p style="color:#555; font-size: 12px; margin-top:10px;">
      📅 <b>Generated:</b> ${new Date().toLocaleString()}<br>
      🔗 <b>Source:</b> QueryTel Sentinel SOC Monitoring System
    </p>
  </div>
  `,
      departmentId: DEPT_ID,
      contactId: contact.id,
      priority: "High",
      status: "Open",
      channel: "Web",
    };

    // --- Send ticket to Zoho Desk ---
    const response = await axios.post(`${DESK_BASE}/tickets`, ticketData, {
      headers: {
        Authorization: `Zoho-oauthtoken ${accessToken}`,
        orgId: ORG_ID,
        "Content-Type": "application/json",
      },
    });

    console.log("🎫 Zoho Ticket Created:", response.data.id);
    return `✅ Ticket created successfully (ID: ${response.data.id})`;
  } catch (err) {
    // --- Detailed error reporting ---
    const detail = err.response?.data || err.message;
    console.error("❌ Zoho Ticket Error:", JSON.stringify(detail, null, 2));

    // Return human-readable message for frontend/cURL
    if (err.response?.data) {
      return `❌ Zoho API Error: ${JSON.stringify(err.response.data, null, 2)}`;
    }
    return `❌ Error creating Zoho ticket: ${err.message}`;
  }
}

/**
 * List tickets from Zoho Desk
 */
export async function listZohoTickets(params = {}) {
  try {
    const accessToken = await getAccessToken();
    if (!accessToken) {
      console.log("⚠️ Zoho access token could not be retrieved");
      return { error: "Zoho authentication failed" };
    }

    const { limit = 50, from = 0, status = "all" } = params;

    // Construct query params
    let url = `${DESK_BASE}/tickets?limit=${limit}&from=${from}&departmentId=${DEPT_ID}`;
    if (status !== "all") {
      url += `&status=${status}`;
    }

    const response = await axios.get(url, {
      headers: {
        Authorization: `Zoho-oauthtoken ${accessToken}`,
        orgId: ORG_ID,
      },
    });

    return {
      tickets: response.data.data || [],
      count: response.data.data?.length || 0
    };
  } catch (err) {
    const detail = err.response?.data || err.message;
    console.error("❌ Zoho List Tickets Error:", JSON.stringify(detail, null, 2));
    throw new Error(err.response?.data?.message || err.message);
  }
}
